# /netlify.toml - FINAL CORRECTED VERSION

[build]
  # Tell Netlify to do all its work inside the "frontend" folder
  base    = "frontend"
  
  # The command to build the site
  command = "npm run build"
  
  # The folder that contains the finished site, RELATIVE to the base.
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200