# /netlify.toml - FINAL CORRECTED VERSION

[build]
  # This tells Netlify where to run the build command
  base    = "frontend"
  
  # This is the command to build the site
  command = "npm run build"
  
  # This is the directory (relative to the base) that contains the finished site
  publish = "dist"

[[redirects]]
  # This is the rewrite rule for Single-Page Applications
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://orchid-nexus-backend.onrender.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://orchid-nexus-backend.onrender.com wss://orchid-nexus-backend.onrender.com;"